export const GET_INGRIDIENTS_REQUEST = 'GET_INGRIDIENTS_REQUEST'
export const GET_INGRIDIENTS_FAILED = 'GET_INGRIDIENTS_FAILED'
export const GET_INGRIDIENTS_SUCCESS = 'GET_INGRIDIENTS_SUCCESS'

export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST'
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED'
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS'
export const CLEAR_ORDER = 'CLEAR_ORDER'

export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'

export const ADD_INGREDIENT_MODAL = 'ADD_INGREDIENT_MODAL'
export const DELETE_INGREDIENT_MODAL = 'DELETE_INGREDIENT_MODAL'
export const ADD_ORDER_MODAL = 'ADD_ORDER_MODAL'
export const CLOSE_ORDER_MODAL = 'CLOSE_ORDER_MODAL'

export const BUN_SCROLL = 'BUN_SCROLL'
export const MAIN_SCROLL = 'MAIN_SCROLL'
export const SAUCE_SCROLL = 'SAUCE_SCROLL'

export const UPDATE_TYPE = 'UPDATE_TYPE'
export const ADD_TYPE = 'ADD_TYPE'
export const ADD_QTY = 'ADD_QTY'
export const DEL_QTY = 'DEL_QTY'
export const REMOVE_BUN = 'REMOVE_BUN'