export const GET_FEED = 'GET_FEED'
export const GET_FEED_FAILED = 'GET_FEED_FAILED'
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS'

export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const INCREASE_ITEM = 'INCREASE_ITEM'
export const DECREASE_ITEM = 'DECREASE_ITEM'

export const ADD_INGREDIENT_MODAL = 'ADD_INGREDIENT_MODAL'
export const DELETE_INGREDIENT_MODAL = 'DELETE_INGREDIENT_MODAL'
export const ADD_ORDER_MODAL = 'ADD_ORDER_MODAL'
export const CLOSE_ORDER_MODAL = 'CLOSE_ORDER_MODAL'

export const BUN_SCROLL = 'BUN_SCROLL'
export const MAIN_SCROLL = 'MAIN_SCROLL'
export const SAUCE_SCROLL = 'SAUCE_SCROLL'

export const UPDATE_TYPE = 'UPDATE_TYPE'
export const ADD_TYPE = 'ADD_TYPE'
export const ADD_QTY = 'ADD_QTY'
export const REMOVE_BUN = 'REMOVE_BUN'